---
- name: restart postgres
  systemd:
    name: postgresql
    daemon_reload: yes
    state: restarted

- name: stop postgres
  systemd:
    name: postgresql
    state: stopped

- name: start postgres
  systemd:
    name: postgresql
    daemon_reload: yes
    state: started
